<%@page language="java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>
<script charset="utf-8" type="text/javascript" src="jspub/jquery/1.11.3/jquery-1.11.3.min.js"></script>
<script charset="utf-8" type="text/javascript" src="scriptsm/wind/wind-all-0.7.3.js"></script>
<script charset="utf-8" type="text/javascript" src="jspub/lodash/lodash.compat.min.js"></script>
<script charset="utf-8" type="text/javascript" src="jspub/handlebars/handlebars-v4.0.2.js"></script>
<script charset="utf-8" type="text/javascript" src="jspub/dhxsin/4.5/dhtmlx-editor.js"></script>
<script charset="utf-8" type="text/javascript" src="scriptsm/bootstrap/3.3.5/js/bootstrap.js"></script>
<script charset="utf-8" type="text/javascript" src="scriptsm/angular/angular.min.js"></script>
<script charset="utf-8" type="text/javascript" src="jspub/GisMap/GeoUtils.js"></script>
<script charset="utf-8" type="text/javascript" src="jspub/GisMap/ZMap.js"></script>
<script charset="utf-8" type="text/javascript" src="jspub/react/react.js"></script>
<script charset="utf-8" type="text/javascript" src="jspub/react/react-dom.js"></script>
<script charset="utf-8" type="text/javascript" src="jspub/react/browser.min.js"></script>
